# Generated by Django 4.2 on 2025-05-16 06:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChainsawBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CHImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('Distribution/Sale', 'Distribution / Sale'), ('Personal/Legal Use', 'Personal / Legal Use')], max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='cps.chainsawbrand')),
            ],
        ),
        migrations.CreateModel(
            name='CHImportModelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_details', to='cps.chimport')),
            ],
        ),
        migrations.CreateModel(
            name='CHImportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_location', models.CharField(max_length=500)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('dti_sec', 'DTI/SEC'), ('purchase_order', 'Purchase Order'), ('affidavit', 'Affidavit'), ('geotag_photo', 'Geotag Photo')], max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cps.chimport')),
            ],
        ),
    ]
