# Generated by Django 4.2 on 2025-05-19 01:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chimport',
            name='crs_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chimport',
            name='date_applied',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
