# Generated by Django 4.2 on 2025-05-19 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0002_chimport_crs_id_chimport_date_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='chimport',
            name='date_approved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chimport',
            name='estab_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chimport',
            name='estab_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chimport',
            name='estab_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='chimport',
            name='estab_id_dniis',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chimport',
            name='estab_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chimport',
            name='evaluator_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chimport',
            name='reference_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chimport',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chimport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Returned', 'Returned'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='chimport',
            name='survey',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chimport',
            name='crs_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
