# Generated by Django 4.2 on 2025-05-19 03:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0003_chimport_date_approved_chimport_estab_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_id', models.IntegerField()),
                ('reference_no', models.CharField(max_length=100)),
                ('forwarded_by_id', models.IntegerField()),
                ('forwarded_to_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('days_pending', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ch_application',
            },
        ),
    ]
