# Generated by Django 4.2 on 2025-05-19 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0004_chapplication'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chainsawbrand',
            table='chahinsawbrand',
        ),
        migrations.AlterModelTable(
            name='chimport',
            table='chimport',
        ),
        migrations.AlterModelTable(
            name='chimportattachment',
            table='chimportattachment',
        ),
        migrations.AlterModelTable(
            name='chimportmodeldetail',
            table='chimportmodeldetail',
        ),
    ]
