# Generated by Django 4.2 on 2025-05-19 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0006_alter_chainsawbrand_table_alter_chimport_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chapplication',
            table='cps_ch_application',
        ),
    ]
