# Generated by Django 4.2 on 2025-05-19 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0007_alter_chapplication_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chapplication',
            table='ch_application',
        ),
    ]
