# Generated by Django 4.2 on 2025-05-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0008_alter_chapplication_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='chimport',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
