# Generated by Django 4.2 on 2025-05-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0009_chimport_arrival_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chimport',
            name='is_existing_permittee',
            field=models.BooleanField(default=False),
        ),
    ]
