# Generated by Django 4.2 on 2025-05-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0010_chimport_is_existing_permittee'),
    ]

    operations = [
        migrations.AddField(
            model_name='chimport',
            name='warehouse_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chimport',
            name='warehouse_city',
            field=models.TextField(blank=True, null=True),
        ),
    ]
