# Generated by Django 4.2 on 2025-05-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0011_chimport_warehouse_address_chimport_warehouse_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHUserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ch_access_level',
            },
        ),
    ]
