# Generated by Django 4.2 on 2025-06-16 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0012_chuseraccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('app_id', models.IntegerField()),
                ('op_id', models.IntegerField()),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('or_no', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fund_cluster', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ch_payment',
            },
        ),
        migrations.CreateModel(
            name='ProofOfPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_location', models.CharField(max_length=500)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='cps.chpayment')),
            ],
            options={
                'db_table': 'proof_of_payment',
            },
        ),
    ]
