# Generated by Django 4.2 on 2025-06-16 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0013_chpayment_proofofpayment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proofofpayment',
            table='ch_proof_of_payment',
        ),
    ]
