# Generated by Django 4.2 on 2025-06-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0014_alter_proofofpayment_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chpayment',
            name='op_id',
            field=models.CharField(max_length=100),
        ),
    ]
