# Generated by Django 4.2 on 2025-06-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0015_alter_chpayment_op_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chpayment',
            name='or_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
