# Generated by Django 4.2 on 2025-06-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0016_alter_chpayment_or_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chpayment',
            name='status',
            field=models.CharField(help_text='0 = Unpaid, 1 = Paid, 2 = Validated', max_length=50),
        ),
    ]
