# Generated by Django 4.2 on 2025-06-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0017_alter_chpayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chpayment',
            name='lbp_ref_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
