# Generated by Django 4.2 on 2025-06-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0018_chpayment_lbp_ref_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='chpayment',
            name='date_confirmed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
