# Generated by Django 4.2 on 2025-06-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0019_chpayment_date_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='chimport',
            name='app_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
