# Generated by Django 4.2 on 2025-06-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0020_chimport_app_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chimport',
            name='app_type',
        ),
    ]
