# Generated by Django 4.2 on 2025-06-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0021_remove_chimport_app_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chimport',
            name='action_officer_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chimport',
            name='evaluator_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
