# Generated by Django 4.2 on 2025-07-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0023_inspectionreport_inspectionattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionattachment',
            name='file',
        ),
        migrations.AddField(
            model_name='inspectionattachment',
            name='file_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
