# Generated by Django 4.2 on 2025-07-17 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0024_remove_inspectionattachment_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.IntegerField()),
                ('cc1', models.SmallIntegerField(blank=True, null=True)),
                ('cc2', models.SmallIntegerField(blank=True, null=True)),
                ('cc3', models.SmallIntegerField(blank=True, null=True)),
                ('cc41', models.SmallIntegerField(blank=True, null=True)),
                ('cc42', models.SmallIntegerField(blank=True, null=True)),
                ('cc43', models.SmallIntegerField(blank=True, null=True)),
                ('cc44', models.SmallIntegerField(blank=True, null=True)),
                ('cc45', models.SmallIntegerField(blank=True, null=True)),
                ('cc46', models.SmallIntegerField(blank=True, null=True)),
                ('cc47', models.SmallIntegerField(blank=True, null=True)),
                ('cc48', models.SmallIntegerField(blank=True, null=True)),
                ('cc49', models.SmallIntegerField(blank=True, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='cps.chimport')),
            ],
        ),
    ]
