# Generated by Django 4.2.21 on 2025-07-25 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0025_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainsawModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='cps.chainsawbrand')),
            ],
            options={
                'unique_together': {('brand', 'model_name')},
            },
        ),
    ]
