# Generated by Django 4.2.21 on 2025-07-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0026_chainsawmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofofpayment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
