# Generated by Django 4.2.21 on 2025-07-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0028_remove_proofofpayment_remarks_chpayment_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='chimportattachment',
            name='is_old',
            field=models.BooleanField(default=False),
        ),
    ]
