# Generated by Django 4.2.21 on 2025-07-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0029_chimportattachment_is_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofofpayment',
            name='is_old',
            field=models.BooleanField(default=False),
        ),
    ]
