# Generated by Django 4.2.21 on 2025-08-07 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0031_chpayment_is_old'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chimport',
            old_name='warehouse_address',
            new_name='warehouse_id',
        ),
        migrations.RemoveField(
            model_name='chimport',
            name='warehouse_city',
        ),
        migrations.CreateModel(
            name='CHImportWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('ch_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='cps.chimport')),
            ],
        ),
    ]
