# Generated by Django 4.2.21 on 2025-08-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0032_rename_warehouse_address_chimport_warehouse_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chimportwarehouse',
            old_name='ch_import',
            new_name='application',
        ),
    ]
