# Generated by Django 4.2.21 on 2025-08-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0033_rename_ch_import_chimportwarehouse_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chimport',
            name='warehouse_id',
        ),
    ]
