# Generated by Django 4.2.21 on 2025-09-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0034_remove_chimport_warehouse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chimport',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chimport',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
